name: compile
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile CV.typ --font-path fonts CV.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: CV
          path: CV.pdf