name: compile
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile CV.typ --font-path fonts CV.pdf
      - run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.ref_name }} - ${{ env.DATE }}"
          files: CV.pdf
          tag_name: latest